name: CI build

on:
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CI release"]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    # Main build job used to
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v2

      # Setup the jdk using version 11 of adoptOpenJDK
      - name: Setup java 11 using adoptOpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      # Build the project using
      #   - clean : clean up the workspace
      #   - validate : perform different check like the dependency and plugin version update
      #   - compile : compile the source code.
      #   - test : Perform the tests.
      - name: Build
        run: mvn -ntp clean validate compile test javadoc:test-javadoc

      # Check changelog update
      - name: Check changelog update
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changelog:
              - 'docs/CHANGELOG.md'
        if: github.event_name != 'workflow_dispatch'

      - if: steps.changes.outputs.changelog == 'false' && github.event_name != 'workflow_dispatch'
        run: exit 1