name: CI build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
        
      - name: Build
        run: mvn clean verify package
